### ISSUE TITLE
cli tool

### ISSUE THREAD

**Issue by travi** [form8ion/utils-cli#3]
mostly for running [the scaffolder](https://github.com/travi/project-scaffolder) for now, but also for other tools, like the [travis-token-updater](https://github.com/travi/travis-token-updater).

similar to [my personal one](https://github.com/travi/cli), but i think it would be worth giving [yargs](https://www.npmjs.com/package/yargs) a try instead of [commander](https://www.npmjs.com/package/commander) for this one.

configure the scaffolder to use:
- [x] commitlint config (form8ion/meta#5)
- [x] eslint config (form8ion/meta#2)
- [x] babel preset (form8ion/meta#3)
- [x] remark-lint preset (form8ion/meta#4)
